oss:
  accessKeyId: LTAI5tH5Npb8Wq1F4vWoqgiLad
  accessKeySecret: X9j1kEWXEF6ZEtdtBplHB6gZFqANJCf
  host: http://quli-ota-test.oss-cn-hangzhou.aliyuncs.com
  uploadDir: firmware/fadsfads
  expireTime: 6199